/**
 * STDTech Group Pvt Ltd — Server-side Data Store
 * In-memory repository with full relational integrity & seeded data.
 * Ready to sync with PostgreSQL when DATABASE_URL is configured.
 */

import {
  User,
  ServiceItem,
  ProductItem,
  ProjectItem,
  CourseItem,
  CertificateItem,
  JobItem,
  ApplicationItem,
  BlogPostItem,
  ContactMessageItem,
  SupportTicketItem,
  AuditLogItem,
  NotificationItem,
  StudentEnrollment,
} from '../src/types.js';

export class DataStore {
  // Pre-configured users with passwords (hashed simulation)
  users: (User & { passwordHash: string })[] = [
    {
      id: 'usr-admin-01',
      email: 'admin@stdtechgroup.com',
      fullName: 'Harinath Verma',
      role: 'admin',
      phone: '7318514528',
      createdAt: '2026-01-10T10:00:00Z',
      passwordHash: 'scrypt$stdtech-demo-salt-2026$15ce55dabfbff1f7bf9aa4f5a7576667f5ce315c3ae6f20ee0c484b5e4a0de737d72a3b1287ee4960fc6aaa127c9078b4f42c5db24d1bcf779073e70e17b963a',
    },
    {
      id: 'usr-staff-01',
      email: 'staff@stdtechgroup.com',
      fullName: 'Akash Verma',
      role: 'staff',
      phone: '7318514528',
      createdAt: '2026-01-15T11:00:00Z',
      passwordHash: 'scrypt$stdtech-demo-salt-2026$15ce55dabfbff1f7bf9aa4f5a7576667f5ce315c3ae6f20ee0c484b5e4a0de737d72a3b1287ee4960fc6aaa127c9078b4f42c5db24d1bcf779073e70e17b963a',
    },
    {
      id: 'usr-student-01',
      email: 'student@stdtechgroup.com',
      fullName: 'Aditya Sharma',
      role: 'student',
      phone: '9876543210',
      createdAt: '2026-02-01T09:30:00Z',
      passwordHash: 'scrypt$stdtech-demo-salt-2026$15ce55dabfbff1f7bf9aa4f5a7576667f5ce315c3ae6f20ee0c484b5e4a0de737d72a3b1287ee4960fc6aaa127c9078b4f42c5db24d1bcf779073e70e17b963a',
    },
    {
      id: 'usr-customer-01',
      email: 'client@stdtechgroup.com',
      fullName: 'Rajesh Gupta',
      role: 'customer',
      phone: '9812345678',
      createdAt: '2026-02-15T14:20:00Z',
      passwordHash: 'scrypt$stdtech-demo-salt-2026$15ce55dabfbff1f7bf9aa4f5a7576667f5ce315c3ae6f20ee0c484b5e4a0de737d72a3b1287ee4960fc6aaa127c9078b4f42c5db24d1bcf779073e70e17b963a',
    },
  ];

  services: ServiceItem[] = [
    {
      id: 'srv-01',
      slug: 'web-mobile-app-development',
      title: 'Web & Mobile App Development',
      shortDescription: 'Modern, high-performance web applications and cross-platform mobile apps tailored for scale, speed, and real-time responsiveness.',
      detailedDescription: 'STDTech Group designs and engineers robust, scalable web platforms and native/cross-platform mobile applications. From interactive React/Vite frontends to resilient Node.js backends and cloud APIs, our solutions are engineered for peak conversion and reliability.',
      icon: 'Code2',
      features: [
        'Single Page & Progressive Web Apps (SPA/PWA)',
        'Cross-platform iOS & Android mobile apps with React Native / Flutter',
        'Enterprise microservices & RESTful / GraphQL API architectures',
        'Headless CMS & high-performance e-commerce platforms',
        'Real-time data synchronization & interactive dashboards',
      ],
      techStack: ['React', 'TypeScript', 'Vite', 'Tailwind CSS', 'Node.js', 'Express', 'PostgreSQL', 'Flutter'],
      process: [
        { step: 1, title: 'Discovery & UX Architecture', desc: 'Understanding business goals, user personas, wireframing, and component design.' },
        { step: 2, title: 'Agile Development', desc: 'Modular frontend implementation, clean typed API contracts, and rapid iterative sprints.' },
        { step: 3, title: 'Quality Assurance & Security', desc: 'Automated testing, vulnerability scanning, accessibility auditing, and load verification.' },
        { step: 4, title: 'Deployment & CI/CD', desc: 'Containerized deployment on Cloud Run/AWS, custom domain setup, and monitoring.' },
      ],
      benefits: [
        'Lightning-fast page load speeds and SEO advantages',
        'Modular, maintainable codebase that easily scales as you grow',
        'Mobile-first responsive design across all devices and orientations',
        'Strict adherence to accessibility (WCAG AA) and security best practices',
      ],
      displayOrder: 1,
    },
    {
      id: 'srv-02',
      slug: 'ai-machine-learning-solutions',
      title: 'AI & Machine Learning Solutions',
      shortDescription: 'Custom predictive analytics, intelligent classification algorithms, and autonomous digital assistants that convert raw data into actionable impact.',
      detailedDescription: 'We harness cutting-edge machine learning and artificial intelligence to automate complex business workflows, predict high-value outcomes, and build context-aware platforms like our upcoming SWAYNIS digital assistant.',
      icon: 'BrainCircuit',
      features: [
        'Predictive modeling (credit risk, product return, healthcare diagnosis)',
        'Natural Language Processing (NLP) & conversational assistants',
        'Customer segmentation & clustering models',
        'Custom neural networks & scikit-learn statistical pipelines',
        'End-to-end MLOps: model training, validation, API deployment, and monitoring',
      ],
      techStack: ['Python', 'TensorFlow', 'PyTorch', 'Scikit-learn', 'FastAPI', 'Pandas', 'PostgreSQL', 'Gemini API'],
      process: [
        { step: 1, title: 'Data Assessment & Cleansing', desc: 'Auditing existing datasets, feature engineering, and normalization.' },
        { step: 2, title: 'Model Prototyping & Benchmarking', desc: 'Training baseline models, hyperparameter tuning, and cross-validation.' },
        { step: 3, title: 'Production API Wrapping', desc: 'Exposing models through low-latency REST microservices with containerization.' },
        { step: 4, title: 'Continuous Feedback Loops', desc: 'Monitoring drift, telemetry tracking, and periodic retrain schedules.' },
      ],
      benefits: [
        'Data-driven decision making with measurable precision and recall',
        'Automate manual administrative tasks and reduce human error',
        'Early anomaly detection and proactive risk mitigation',
        'Proprietary competitive edge tailored to your exact industry domain',
      ],
      displayOrder: 2,
    },
    {
      id: 'srv-03',
      slug: 'software-business-solutions',
      title: 'Software & Business Solutions',
      shortDescription: 'Custom Enterprise Resource Planning (ERP), CRM tools, automated reporting systems, and specialized industrial design software.',
      detailedDescription: 'Every business has distinct operational bottlenecks. STDTech Group engineers purpose-built internal tools, inventory management engines, and CAD integration utilities to streamline day-to-day enterprise operations.',
      icon: 'Cpu',
      features: [
        'Custom Business Process Management (BPM) systems',
        'Inventory, billing, and automated invoicing pipelines',
        'CAD and engineering automation (AutoCAD script integration)',
        'Role-Based Access Control (RBAC) portals for staff & clients',
        'Seamless integration with third-party payment & communications APIs',
      ],
      techStack: ['Node.js', 'Express', 'TypeScript', 'PostgreSQL', 'AutoCAD API', 'Docker', 'Redis'],
      process: [
        { step: 1, title: 'Workflow Audit', desc: 'Analyzing bottlenecks in paperwork, spreadsheets, and manual tracking.' },
        { step: 2, title: 'Architecture & Database Design', desc: 'Constructing normalized schemas with strict foreign keys and audit logs.' },
        { step: 3, title: 'System Build & Integration', desc: 'Developing intuitive dashboards and role-specific views.' },
        { step: 4, title: 'Staff Training & Handover', desc: 'Comprehensive documentation, live training, and dedicated support.' },
      ],
      benefits: [
        'Eliminate repetitive data entry and save hundreds of employee hours',
        'Centralized, single source of truth for company data and analytics',
        'Zero per-seat licensing fees of bloated off-the-shelf software',
        'Rock-solid data confidentiality and internal security',
      ],
      displayOrder: 3,
    },
    {
      id: 'srv-04',
      slug: 'cybersecurity-cloud-solutions',
      title: 'Cybersecurity & Cloud Solutions',
      shortDescription: 'Enterprise cloud infrastructure, container orchestration, hardened firewall configs, and proactive vulnerability protection.',
      detailedDescription: 'Secure your digital presence with STDTech Group’s cloud architecture and cybersecurity standards. We implement zero-trust access control, automated backups, encrypted data transfers, and defense-in-depth protection.',
      icon: 'ShieldCheck',
      features: [
        'Cloud infrastructure setup (GCP, AWS, DigitalOcean) with automated scaling',
        'Docker containerization & secure deployment pipelines',
        'OWASP Top 10 vulnerability prevention (XSS, CSRF, SQLi protection)',
        'SSL/TLS encryption, DNS management, and reverse proxy configuration',
        'Automated database snapshots, disaster recovery, and audit logging',
      ],
      techStack: ['Nginx', 'Docker', 'Google Cloud Platform', 'AWS', 'PostgreSQL', 'Linux', 'Cloudflare'],
      process: [
        { step: 1, title: 'Vulnerability & Risk Audit', desc: 'Scanning existing endpoints, headers, and access policies.' },
        { step: 2, title: 'Infrastructure Hardening', desc: 'Configuring firewalls, SSL, secret management, and network segregation.' },
        { step: 3, title: 'Containerized Deployment', desc: 'Setting up automated build pipelines with isolated environments.' },
        { step: 4, title: '24/7 Monitoring & Logging', desc: 'Structured event tracking and instant alert dispatching.' },
      ],
      benefits: [
        'Minimize downtime and defend against unauthorized breaches',
        '99.9% uptime with automated health checks and failovers',
        'Compliance-ready audit logs and user activity tracking',
        'Optimized server resource consumption and lowered cloud bills',
      ],
      displayOrder: 4,
    },
    {
      id: 'srv-05',
      slug: 'digital-transformation-it-consulting',
      title: 'Digital Transformation & IT Consulting',
      shortDescription: 'Strategic technology advisory, legacy system modernization, and digital roadmap execution for growing enterprises.',
      detailedDescription: 'Transition your business from legacy paper and disconnected tools to modern, unified digital operations. STDTech Group provides grounded, cost-effective architectural consulting for organizations of all sizes.',
      icon: 'Sparkles',
      features: [
        'Digital roadmap planning and technology stack selection',
        'Legacy code refactoring and database migration to modern PostgreSQL',
        'Paper-to-Cloud workflow digitization',
        'Tech team enablement, code reviews, and architecture audits',
        'Custom domain setup, email server configuration, and brand online presence',
      ],
      techStack: ['Architecture Strategy', 'Cloud Migration', 'Microservices', 'API First', 'DevOps'],
      process: [
        { step: 1, title: 'Technology Readiness Assessment', desc: 'Evaluating current tools, workflows, and growth targets.' },
        { step: 2, title: 'Strategic Roadmap', desc: 'Prioritizing high-ROI technical upgrades with realistic timelines.' },
        { step: 3, title: 'Phased Execution', desc: 'Implementing changes without disrupting ongoing day-to-day business.' },
        { step: 4, title: 'Optimization & Measurement', desc: 'Benchmarking operational improvements and refining solutions.' },
      ],
      benefits: [
        'Clarity and confidence in technical investments and tooling choices',
        'Smooth transitions with zero data loss or operational halt',
        'Future-proof architectures ready for AI and modern API integrations',
        'Direct access to senior technology architects',
      ],
      displayOrder: 5,
    },
  ];

  products: ProductItem[] = [
    {
      id: 'prod-01',
      slug: 'swaynis',
      name: 'SWAYNIS',
      category: 'AI Digital Assistant',
      description: 'An advanced AI-powered autonomous digital assistant and intelligence platform engineered to streamline communications, analyze complex datasets, and assist business users.',
      problem: 'Small and medium businesses struggle with fragmented communication, repetitive customer queries, and lack of real-time insights from unstructured business data.',
      solution: 'SWAYNIS unifies contextual AI agents, natural language query engines, and automated task execution into a single intelligent platform.',
      features: [
        'Context-aware conversational intelligence',
        'Automated workflow scheduling and reminders',
        'Natural language document querying and summarization',
        'Seamless API connectors for databases and CRM tools',
        'Privacy-preserving local and secure cloud inference modes',
      ],
      technology: ['Python', 'FastAPI', 'Node.js', 'React', 'TypeScript', 'Vector Embeddings', 'PostgreSQL'],
      status: 'COMING SOON',
      isFeatured: true,
    },
    {
      id: 'prod-02',
      slug: 'autocad-project',
      name: 'AutoCAD Project Automation',
      category: 'Engineering & CAD Utility',
      description: 'Specialized computer-aided drafting and parametric modeling utility designed to automate repetitive mechanical and architectural CAD drafting routines.',
      problem: 'Engineering teams spend hours manually redrawing repetitive geometries, updating title blocks, and recalculating dimensional tolerances.',
      solution: 'A custom automation engine that interfaces directly with AutoCAD files to batch-generate standard components, extract bills of materials, and ensure drafting standards.',
      features: [
        'Automated geometric generation from spreadsheet input',
        'Batch export and layer normalization across dozens of DWG/DXF files',
        'Title block metadata synchronizer',
        'Dimension validation and collision check alerts',
      ],
      technology: ['AutoCAD API', 'AutoLISP', 'Python', 'C# .NET', 'Desktop Integration'],
      status: 'Active Prototype',
      isFeatured: true,
    },
    {
      id: 'prod-03',
      slug: 'loan-approval-prediction-system',
      name: 'Loan Approval Prediction System',
      category: 'FinTech & Machine Learning',
      description: 'A machine learning classification system that evaluates loan applicant creditworthiness, debt-to-income ratios, and financial history to predict loan approval probabilities.',
      problem: 'Traditional financial institutions face backlogs in manual loan application reviews, leading to slow turnaround times and subjective evaluation discrepancies.',
      solution: 'An automated, bias-mitigated predictive scoring model that delivers instant preliminary approval likelihood and transparent risk factor breakdowns.',
      features: [
        'Multi-factor credit risk evaluation (income, credit score, loan term, dependents)',
        'Explainable AI feature importance charts (SHAP values)',
        'Real-time decisioning API with sub-100ms response time',
        'Interactive financial officer dashboard for manual review overrides',
      ],
      technology: ['Python', 'Scikit-Learn', 'XGBoost', 'Pandas', 'Flask / Express', 'Tailwind CSS'],
      status: 'Active Prototype',
      isFeatured: true,
    },
    {
      id: 'prod-04',
      slug: 'product-return-prediction-system',
      name: 'Product Return Prediction System',
      category: 'E-Commerce Intelligence',
      description: 'Predictive analytics software for e-commerce and retail merchants that identifies high-probability product return transactions before fulfillment.',
      problem: 'E-commerce businesses suffer heavy reverse-logistics shipping costs and inventory depreciation due to high, unexpected product return rates.',
      solution: 'A machine learning system analyzing customer purchase history, sizing patterns, shipping destinations, and category return rates to predict return risk.',
      features: [
        'Pre-shipment risk scoring for incoming online orders',
        'Customer sizing discrepancy alerts and proactive size verification prompt triggers',
        'Category-level return insights dashboard',
        'Automated recommendations for optimal return policies per product tier',
      ],
      technology: ['Python', 'RandomForest', 'PostgreSQL', 'Node.js', 'React', 'Chart.js'],
      status: 'Active Prototype',
      isFeatured: false,
    },
    {
      id: 'prod-05',
      slug: 'heart-disease-prediction-system',
      name: 'Heart Disease Prediction System',
      category: 'HealthTech & Predictive ML',
      description: 'A clinical diagnostic decision-support system utilizing biometric inputs and historical clinical data to assess early cardiovascular disease indicators.',
      problem: 'Early stages of cardiovascular disorders often go undetected without comprehensive, costly laboratory testing, especially in underserved rural regions.',
      solution: 'A lightweight, accessible screening tool providing preliminary risk categorization based on non-invasive clinical biomarkers (blood pressure, cholesterol, resting ECG, age, max heart rate).',
      features: [
        'Biometric parameter risk calculator with immediate risk score',
        'Visual indicators for critical cardiovascular metrics',
        'Exportable clinical summary reports for healthcare practitioners',
        'Designed to run efficiently on low-bandwidth and mobile devices',
      ],
      technology: ['Python', 'Logistic Regression & SVM', 'NumPy', 'React', 'TypeScript', 'Tailwind'],
      status: 'Active Prototype',
      isFeatured: false,
    },
    {
      id: 'prod-06',
      slug: 'mobile-user-segment-system',
      name: 'Mobile User Segment System',
      category: 'Mobile Analytics & Clustering',
      description: 'Unsupervised machine learning clustering platform that categorizes mobile application users based on behavioral telemetry, session duration, and feature engagement.',
      problem: 'Application developers often struggle to personalize engagement campaigns because user cohorts are manually defined or too broad.',
      solution: 'Automated K-Means clustering algorithm that dynamically groups active users into distinct behavioral personas for targeted push notifications and feature rollouts.',
      features: [
        'Unsupervised K-Means clustering with optimal cluster (Elbow method) discovery',
        'Cohort visualization and churn risk identification',
        'Engagement telemetry ingestion API',
        'Exportable segment lists for targeted marketing and onboarding flows',
      ],
      technology: ['Python', 'Scikit-Learn', 'K-Means', 'Express.js', 'D3.js / Recharts', 'PostgreSQL'],
      status: 'Active Prototype',
      isFeatured: false,
    },
  ];

  portfolio: ProjectItem[] = [
    {
      id: 'proj-01',
      slug: 'swaynis-ai-assistant',
      title: 'SWAYNIS — AI-Powered Digital Assistant',
      category: 'Artificial Intelligence',
      description: 'Next-generation AI digital assistant built for intelligent task automation, natural language reasoning, and cross-platform productivity.',
      technology: ['Python', 'FastAPI', 'Node.js', 'React', 'TypeScript', 'PostgreSQL'],
      details: 'SWAYNIS represents STDTech Group’s flagship artificial intelligence platform. Designed from the ground up for privacy, speed, and contextual reasoning, it bridges the gap between conversational AI and operational software execution.',
      status: 'In Development',
    },
    {
      id: 'proj-02',
      slug: 'loan-approval-prediction',
      title: 'Loan Approval Prediction System',
      category: 'Machine Learning',
      description: 'FinTech algorithmic scoring application predicting loan eligibility with 94%+ cross-validated precision on standardized credit datasets.',
      technology: ['Python', 'Scikit-Learn', 'Pandas', 'Flask API', 'React', 'Tailwind CSS'],
      details: 'Trained on historical applicant metrics including income, credit history, loan amount, and property area. Incorporates feature importance transparency to prevent discriminatory bias.',
      status: 'Completed',
    },
    {
      id: 'proj-03',
      slug: 'product-return-prediction',
      title: 'Product Return Prediction System',
      category: 'E-Commerce Analytics',
      description: 'Reverse-logistics optimization algorithm for digital retail merchants, reducing return processing overhead through predictive risk classification.',
      technology: ['Python', 'Random Forest', 'PostgreSQL', 'Express', 'TypeScript'],
      details: 'Analyzes user behavioral signals, order sizes, product return frequency, and delivery zones to alert merchants to high-risk transactions before fulfillment.',
      status: 'Completed',
    },
    {
      id: 'proj-04',
      slug: 'heart-disease-prediction',
      title: 'Heart Disease Prediction System',
      category: 'Healthcare AI',
      description: 'Biometric cardiovascular risk assessment model assisting rural clinics and individuals with early preliminary health screenings.',
      technology: ['Python', 'Support Vector Machines', 'React', 'TypeScript', 'Tailwind CSS'],
      details: 'Evaluates parameters such as resting blood pressure, cholesterol, fasting blood sugar, and exercise induced angina to compute clinical risk categorizations.',
      status: 'Completed',
    },
    {
      id: 'proj-05',
      slug: 'mobile-user-segment',
      title: 'Mobile User Segment System',
      category: 'Data Science & Clustering',
      description: 'Behavioral clustering engine mapping mobile app users into actionable cohorts for retention and personalized notifications.',
      technology: ['Python', 'K-Means Clustering', 'Matplotlib', 'Express', 'Tailwind CSS'],
      details: 'Enables product teams to uncover hidden behavioral patterns, churn tendencies, and power-user demographics through automated clustering routines.',
      status: 'Completed',
    },
    {
      id: 'proj-06',
      slug: 'autocad-project-automation',
      title: 'AutoCAD Project Automation',
      category: 'Engineering & CAD',
      description: 'Automated drafting utilities reducing drafting turnaround times for mechanical components and standardized layouts.',
      technology: ['AutoLISP', 'AutoCAD API', 'Python', 'Drafting Automation'],
      details: 'Custom script modules that automate repetitive drawing procedures, generate parametric drafting components, and batch-produce fabrication-ready drawings.',
      status: 'Completed',
    },
    {
      id: 'proj-07',
      slug: 'stdtech-group-official-platform',
      title: 'STDTech Group Official Website',
      category: 'Web Platform & Cloud Architecture',
      description: 'Production-ready full-stack enterprise web portal, academy management system, and certificate verification engine for STDTech Group Pvt Ltd.',
      technology: ['React 19', 'TypeScript', 'Vite', 'Tailwind CSS v4', 'Express', 'PostgreSQL Schema', 'QR Engine'],
      details: 'Engineered as the primary digital home and operations hub of STDTech Group Pvt Ltd. Features 30 dedicated pages, interactive 3D particle digital ecosystem, role-based dashboards, and QR-code verified certificate issuance.',
      demoUrl: 'https://stdtechgroup.com',
      githubUrl: 'https://github.com/harinath78811388-crypto',
      status: 'Completed',
    },
  ];

  courses: CourseItem[] = [
    {
      id: 'crs-01',
      slug: 'programming-software-development',
      title: 'Programming & Software Development Masterclass',
      category: 'Programming & Software Development',
      overview: 'Master foundational computer science, algorithm design, data structures, and object-oriented programming in Python, C++, and Java.',
      curriculum: [
        { module: 'Module 1: Logic Building & Algorithm Fundamentals', topics: ['Flowcharts & Pseudocode', 'Variables, Control Flow & Loops', 'Memory & Pointers'] },
        { module: 'Module 2: Data Structures & Algorithms (DSA)', topics: ['Arrays, Linked Lists, Stacks, Queues', 'Trees, Graphs, & Hash Maps', 'Searching, Sorting & Time Complexity (Big O)'] },
        { module: 'Module 3: Object-Oriented Software Design', topics: ['Classes, Encapsulation, Inheritance, Polymorphism', 'SOLID Principles & Design Patterns', 'Clean Code Practices'] },
        { module: 'Module 4: Real-world Software Project', topics: ['Git Version Control & GitHub', 'Automated Testing with Jest/PyTest', 'Building a Command Line & GUI Application'] },
      ],
      duration: '4 Months (160 Hours)',
      skillLevel: 'Beginner',
      learningOutcomes: [
        'Solve complex coding interview challenges and competitive programming problems',
        'Write clean, modular, and maintainable software architectures',
        'Build and publish open-source repositories on GitHub',
      ],
      projects: ['Terminal Banking Simulation System', 'Custom Graph Algorithm Visualizer', 'Desktop File Encryption Utility'],
      certificateIncluded: true,
      isActive: true,
    },
    {
      id: 'crs-02',
      slug: 'web-mobile-app-development-bootcamp',
      title: 'Full-Stack Web & Mobile App Development Bootcamp',
      category: 'Web & Mobile App Development',
      overview: 'Comprehensive hands-on training covering modern React, TypeScript, Node.js, Express, PostgreSQL, and cross-platform mobile app development.',
      curriculum: [
        { module: 'Module 1: Modern Frontend with React & Tailwind', topics: ['Semantic HTML & CSS Grid/Flexbox', 'React Hooks, State Management & Routing', 'Tailwind CSS & Responsive Design'] },
        { module: 'Module 2: Backend Architecture with Node.js & Express', topics: ['RESTful API Design & Middleware', 'Authentication with JWT & Password Hashing', 'Input Validation & Error Handling'] },
        { module: 'Module 3: Relational Database Engineering with PostgreSQL', topics: ['Relational Schema Design & Normalization', 'SQL Queries, Joins, Indexes & Constraints', 'ORM / Query Builders'] },
        { module: 'Module 4: Mobile Application Development', topics: ['React Native / Flutter Setup', 'Mobile Navigation & Offline Storage', 'Publishing to App Stores'] },
      ],
      duration: '6 Months (240 Hours)',
      skillLevel: 'All Levels',
      learningOutcomes: [
        'Architect, build, and deploy production-grade full-stack web applications',
        'Implement secure user authentication and role-based permissions',
        'Deploy applications to cloud platforms with custom domains and SSL',
      ],
      projects: ['Full-Featured E-Commerce Marketplace', 'Real-Time Team Collaboration Board', 'Cross-Platform Mobile Task Manager'],
      certificateIncluded: true,
      isActive: true,
    },
    {
      id: 'crs-03',
      slug: 'ai-machine-learning-data-science',
      title: 'AI, Machine Learning & Data Science Engineering',
      category: 'AI, Machine Learning & Data Science',
      overview: 'Practical data science and machine learning from exploratory data analysis to deploying predictive neural networks in production.',
      curriculum: [
        { module: 'Module 1: Data Analysis & Statistical Foundations', topics: ['NumPy, Pandas & Data Wrangling', 'Matplotlib & Seaborn Data Visualization', 'Probability, Statistics & Hypothesis Testing'] },
        { module: 'Module 2: Classical Machine Learning Algorithms', topics: ['Linear & Logistic Regression', 'Decision Trees, Random Forests & Gradient Boosting (XGBoost)', 'K-Means Clustering & PCA'] },
        { module: 'Module 3: Deep Learning & Neural Networks', topics: ['Artificial Neural Networks (ANNs)', 'Computer Vision with CNNs', 'Natural Language Processing (NLP) with Transformers'] },
        { module: 'Module 4: MLOps & Production Deployment', topics: ['Model Serialization & Dockerization', 'FastAPI Microservice Creation', 'Monitoring Model Drift & Continuous Training'] },
      ],
      duration: '5 Months (200 Hours)',
      skillLevel: 'Intermediate',
      learningOutcomes: [
        'Build predictive models like loan approval, fraud detection, and return prediction',
        'Clean raw, messy business data into high-value engineered features',
        'Serve trained machine learning models via high-throughput web APIs',
      ],
      projects: ['End-to-End Credit Risk Prediction App', 'Customer Churn Analysis Dashboard', 'Healthcare Image Classifier'],
      certificateIncluded: true,
      isActive: true,
    },
    {
      id: 'crs-04',
      slug: 'cybersecurity-ethical-hacking',
      title: 'Cybersecurity & Ethical Hacking Practitioner',
      category: 'Cybersecurity & Ethical Hacking',
      overview: 'Defensive security, network penetration testing, web application security auditing (OWASP Top 10), and vulnerability assessment.',
      curriculum: [
        { module: 'Module 1: Networking & Security Fundamentals', topics: ['TCP/IP, DNS, OSI Model & Subnetting', 'Linux System Administration & Bash Scripting', 'Cryptography, Hashes & Public Key Infrastructure'] },
        { module: 'Module 2: Web Application Penetration Testing', topics: ['OWASP Top 10 Vulnerabilities (SQLi, XSS, CSRF, SSRF)', 'Burp Suite & Automated Security Scanners', 'Secure Coding & API Security'] },
        { module: 'Module 3: Network Security & Defense', topics: ['Firewalls, IDS/IPS Configuration', 'Wireshark Packet Analysis', 'Hardening Linux & Windows Servers'] },
      ],
      duration: '4 Months (160 Hours)',
      skillLevel: 'Intermediate',
      learningOutcomes: [
        'Conduct ethical penetration tests on web platforms and network nodes',
        'Identify and remediate critical security vulnerabilities before attackers exploit them',
        'Implement robust enterprise defense policies and compliance measures',
      ],
      projects: ['Comprehensive Web Application Security Audit Report', 'Network Vulnerability Scanner Script', 'Secure Authentication Vault Implementation'],
      certificateIncluded: true,
      isActive: true,
    },
    {
      id: 'crs-05',
      slug: 'cloud-computing-devops',
      title: 'Cloud Computing & DevOps Engineering',
      category: 'Cloud Computing & DevOps',
      overview: 'Master cloud architecture, Docker containerization, Kubernetes orchestration, CI/CD automated deployment pipelines, and Infrastructure as Code.',
      curriculum: [
        { module: 'Module 1: Cloud Providers & Core Architecture', topics: ['Google Cloud Platform & AWS Core Services', 'VPC Networks, IAM & Secret Management', 'Cloud Storage & Serverless Functions'] },
        { module: 'Module 2: Containerization with Docker', topics: ['Dockerfiles, Multi-stage Builds & Optimization', 'Docker Compose for Multi-service Stacks', 'Container Security & Registries'] },
        { module: 'Module 3: CI/CD Pipelines & Automation', topics: ['GitHub Actions & Automated Testing', 'Blue/Green & Rolling Deployments', 'Monitoring & Prometheus / Grafana'] },
      ],
      duration: '3 Months (120 Hours)',
      skillLevel: 'Intermediate',
      learningOutcomes: [
        'Deploy scalable containerized applications to cloud platforms with zero downtime',
        'Automate testing, build, and release cycles with GitHub Actions',
        'Monitor server metrics, error logs, and optimize infrastructure costs',
      ],
      projects: ['Automated CI/CD Pipeline for Full-Stack App', 'Multi-Container Microservices Deployment on Cloud Run', 'High-Availability Load Balanced Web Cluster'],
      certificateIncluded: true,
      isActive: true,
    },
    {
      id: 'crs-06',
      slug: 'database-backend-development',
      title: 'Database & Advanced Backend Development',
      category: 'Database & Backend Development',
      overview: 'High-scale backend engineering with PostgreSQL, Redis caching, message queues, and high-concurrency API architectures.',
      curriculum: [
        { module: 'Module 1: Relational Database Mastery (PostgreSQL)', topics: ['Advanced SQL Queries, CTEs & Window Functions', 'Database Indexing Strategies & Query Optimization', 'Transactions, ACID Properties & Isolation Levels'] },
        { module: 'Module 2: Scalable API Architecture', topics: ['Node.js Event Loop & Concurrency Patterns', 'Authentication, Rate Limiting & Security Headers', 'Streaming Large Files & WebSockets'] },
        { module: 'Module 3: Caching & Message Queues', topics: ['Redis in-memory caching strategies', 'Background job workers with BullMQ', 'Database replication & backup automation'] },
      ],
      duration: '3 Months (120 Hours)',
      skillLevel: 'Intermediate',
      learningOutcomes: [
        'Design fault-tolerant database schemas handling millions of rows',
        'Optimize slow database queries and design custom indexes',
        'Build low-latency APIs capable of handling heavy concurrent traffic',
      ],
      projects: ['High-Performance Financial Ledger Database', 'Real-Time Notification Delivery Engine with Redis', 'Automated Database Backup & Migration Runner'],
      certificateIncluded: true,
      isActive: true,
    },
    {
      id: 'crs-07',
      slug: 'networking-it-infrastructure',
      title: 'Networking & IT Infrastructure Administration',
      category: 'Networking & IT Infrastructure',
      overview: 'Hands-on IT administration, enterprise routing, switching, DNS setup, VPNs, server management, and system troubleshooting.',
      curriculum: [
        { module: 'Module 1: Network Protocols & Topologies', topics: ['LAN/WAN, Subnetting, IPv4 & IPv6', 'Routing Protocols (OSPF, BGP) & VLANs', 'DNS, DHCP, NAT & Port Forwarding'] },
        { module: 'Module 2: Server Administration & Virtualization', topics: ['Linux Server Setup & Shell Management', 'Windows Server & Active Directory', 'Virtual Machines & Hypervisors'] },
        { module: 'Module 3: IT Support & Disaster Recovery', topics: ['System Backup Solutions & Recovery Drills', 'Hardware Diagnostics & Performance Profiling', 'Remote Management & Telemetry'] },
      ],
      duration: '3 Months (120 Hours)',
      skillLevel: 'Beginner',
      learningOutcomes: [
        'Configure and troubleshoot corporate office networks and router configurations',
        'Administer production Linux servers securely',
        'Implement robust enterprise backup and recovery protocols',
      ],
      projects: ['Enterprise Virtual Network Setup with VLANs', 'Automated Linux Server Hardening Script', 'Disaster Recovery Plan & Mock Drill'],
      certificateIncluded: true,
      isActive: true,
    },
    {
      id: 'crs-08',
      slug: 'ui-ux-graphic-design',
      title: 'UI/UX & Product Design Engineering',
      category: 'UI/UX & Graphic Design',
      overview: 'Human-centered product design, wireframing, high-fidelity Figma prototyping, typography, design systems, and frontend handoff.',
      curriculum: [
        { module: 'Module 1: UX Research & Information Architecture', topics: ['User Persona Mapping & Problem Statements', 'User Journey Mapping & Wireframing', 'Heuristic Evaluation & Usability Testing'] },
        { module: 'Module 2: UI Design & Design Systems in Figma', topics: ['Visual Hierarchy, Spacing Systems & Grids', 'Typography Pairing & Accessible Color Contrast', 'Components, Auto Layout, Variants & Design Tokens'] },
        { module: 'Module 3: Prototyping & Developer Collaboration', topics: ['Interactive Micro-interactions & Smart Animations', 'Design Handoff & CSS Specs', 'Accessibility Audits (WCAG AA)'] },
      ],
      duration: '3 Months (120 Hours)',
      skillLevel: 'Beginner',
      learningOutcomes: [
        'Design complete, modern SaaS and mobile application interfaces in Figma',
        'Create scalable design systems with reusable components and tokens',
        'Deliver developer-ready design specifications with pixel-perfect accuracy',
      ],
      projects: ['FinTech Mobile App UI/UX Redesign', 'Complete Enterprise SaaS Design System in Figma', 'Interactive E-Commerce Checkout Experience Prototype'],
      certificateIncluded: true,
      isActive: true,
    },
    {
      id: 'crs-09',
      slug: 'digital-marketing-business-technology',
      title: 'Digital Marketing & Business Technology',
      category: 'Digital Marketing & Business Technology',
      overview: 'SEO strategies, technical search engine optimization, content marketing, performance analytics, and marketing automation tools.',
      curriculum: [
        { module: 'Module 1: Technical & On-Page SEO', topics: ['Keyword Research & Search Intent', 'Meta Tags, Canonical URLs & Schema.org Structured Data', 'Core Web Vitals & Site Speed Optimization'] },
        { module: 'Module 2: Analytics & Conversion Optimization', topics: ['Google Analytics 4 (GA4) & Tag Manager', 'Funnel Tracking & Heatmap Analysis', 'A/B Testing & Landing Page Optimization'] },
        { module: 'Module 3: Marketing Automation & Brand Presence', topics: ['Email Automation & CRM Integration', 'Social Media Strategy & Content Calendars', 'B2B Lead Generation Workflows'] },
      ],
      duration: '2.5 Months (100 Hours)',
      skillLevel: 'Beginner',
      learningOutcomes: [
        'Rank websites on Google search using ethical technical and content SEO',
        'Analyze user conversion funnels and make data-driven marketing decisions',
        'Set up automated lead capture and nurturing workflows',
      ],
      projects: ['Full Website SEO Audit & Optimization Plan', 'High-Converting Landing Page & Lead Funnel', 'Multi-Channel Digital Marketing Strategy Document'],
      certificateIncluded: true,
      isActive: true,
    },
    {
      id: 'crs-10',
      slug: 'professional-it-career-development',
      title: 'Professional IT & Career Development Accelerator',
      category: 'Professional IT & Career Development',
      overview: 'Resume engineering, GitHub portfolio building, mock technical interviews, freelance project acquisition, and workplace communication.',
      curriculum: [
        { module: 'Module 1: Resume & Personal Brand Engineering', topics: ['ATS-Compliant Technical Resume Writing', 'LinkedIn Profile Optimization & Networking', 'GitHub Profile Curation & Portfolio Presentation'] },
        { module: 'Module 2: Technical Interview Preparation', topics: ['Data Structures & Algorithm Whiteboarding', 'System Design Interview Fundamentals', 'Behavioral Interview Strategies (STAR Method)'] },
        { module: 'Module 3: Freelancing & Professional Growth', topics: ['Client Proposal Writing & Project Scoping', 'Pricing, Invoicing & Contract Basics', 'Agile Workplace Collaboration & Communication'] },
      ],
      duration: '2 Months (80 Hours)',
      skillLevel: 'All Levels',
      learningOutcomes: [
        'Craft an ATS-optimized technical resume that lands interviews',
        'Ace technical coding and behavioral interviews with confidence',
        'Secure remote freelance projects or full-time tech roles',
      ],
      projects: ['Polished Personal Portfolio Website', 'ATS-Optimized Master Tech Resume', 'Recorded Mock Technical Interview Session'],
      certificateIncluded: true,
      isActive: true,
    },
  ];

  certificates: CertificateItem[] = [
    {
      id: 'cert-01',
      certificateId: 'STDT-2026-00001',
      studentName: 'Aditya Sharma',
      courseTitle: 'Full-Stack Web & Mobile App Development Bootcamp',
      courseDuration: '6 Months (240 Hours)',
      completionDate: '2026-08-15',
      issuingOrganization: 'STDTech Group Pvt Ltd',
      status: 'valid',
      qrCodePayload: 'https://stdtechgroup.com/verify/STDT-2026-00001',
      verificationHash: 'sha256:stdt-00001-987642a8b9f7c4',
      createdAt: '2026-08-15T12:00:00Z',
    },
    {
      id: 'cert-02',
      certificateId: 'STDT-2026-00002',
      studentName: 'Pooja Patel',
      courseTitle: 'AI, Machine Learning & Data Science Engineering',
      courseDuration: '5 Months (200 Hours)',
      completionDate: '2026-09-01',
      issuingOrganization: 'STDTech Group Pvt Ltd',
      status: 'valid',
      qrCodePayload: 'https://stdtechgroup.com/verify/STDT-2026-00002',
      verificationHash: 'sha256:stdt-00002-349f82d1e5b8a0',
      createdAt: '2026-09-01T14:30:00Z',
    },
  ];

  jobs: JobItem[] = [
    {
      id: 'job-01',
      title: 'Full-Stack React & Node.js Developer',
      department: 'Engineering',
      jobType: 'Full-time',
      experienceLevel: 'Fresher',
      workplaceType: 'Remote',
      location: 'Remote / Ballia Office',
      description: 'We are expanding our core technical development team. Looking for passionate full-stack developers skilled in React, TypeScript, Node.js, and PostgreSQL to build cutting-edge software solutions and client platforms.',
      requirements: [
        'Strong knowledge of modern JavaScript (ES6+), TypeScript, and React',
        'Familiarity with Node.js, Express, and RESTful API development',
        'Understanding of PostgreSQL, database relationships, and SQL queries',
        'Experience with Git version control and collaborative workflows',
        'Passion for learning new technologies and clean code principles',
      ],
      responsibilities: [
        'Develop responsive web applications and interactive client dashboards',
        'Implement robust RESTful APIs with authentication and validation',
        'Collaborate with founders on architecture decisions and feature specs',
        'Perform testing and participate in code reviews',
      ],
      isActive: true,
      createdAt: '2026-02-10T10:00:00Z',
    },
    {
      id: 'job-02',
      title: 'AI / Machine Learning Engineer (Intern)',
      department: 'Artificial Intelligence',
      jobType: 'Internship',
      experienceLevel: 'Intern',
      workplaceType: 'Remote',
      location: 'Remote',
      description: 'Join our research and product team to work on predictive machine learning systems and our upcoming SWAYNIS digital assistant platform.',
      requirements: [
        'Hands-on experience with Python, Pandas, NumPy, and Scikit-Learn',
        'Familiarity with classification, regression, and clustering algorithms',
        'Ability to write clean, modular scripts and evaluate model metrics',
        'Basic familiarity with FastAPI or Flask is a plus',
      ],
      responsibilities: [
        'Conduct data exploration and feature engineering on real-world datasets',
        'Train and benchmark machine learning models',
        'Assist in building REST API wrappers for model deployment',
        'Document model architectures and evaluation results',
      ],
      isActive: true,
      createdAt: '2026-02-15T12:00:00Z',
    },
    {
      id: 'job-03',
      title: 'UI/UX & Graphic Design Associate',
      department: 'Design',
      jobType: 'Part-time',
      experienceLevel: 'Fresher',
      workplaceType: 'Remote',
      location: 'Remote',
      description: 'Design intuitive, clean, and accessible user interfaces for web and mobile applications, as well as digital marketing assets.',
      requirements: [
        'Proficiency in Figma for wireframing, UI prototyping, and design systems',
        'Strong understanding of color theory, typography, spacing, and mobile responsiveness',
        'Ability to communicate design rationales clearly',
        'Portfolio demonstrating web or mobile UI/UX projects',
      ],
      responsibilities: [
        'Create high-fidelity mockups and interactive prototypes for products',
        'Maintain and expand the STDTech Group design system and brand assets',
        'Collaborate with frontend developers for pixel-perfect implementation',
      ],
      isActive: true,
      createdAt: '2026-02-20T14:00:00Z',
    },
  ];

  applications: ApplicationItem[] = [
    {
      id: 'app-01',
      jobId: 'job-01',
      jobTitle: 'Full-Stack React & Node.js Developer',
      name: 'Rohan Tiwari',
      email: 'rohan.tiwari@example.com',
      phone: '9845123456',
      position: 'Full-Stack Developer',
      experienceYears: 'Fresher (Graduating 2026)',
      education: 'B.Tech in Computer Science',
      resumeFileName: 'Rohan_Tiwari_Resume.pdf',
      portfolioUrl: 'https://github.com/rohan-tiwari-dev',
      coverMessage: 'I have hands-on experience building full-stack applications with React and Express. Eager to contribute to STDTech Group’s growing development team.',
      status: 'reviewing',
      createdAt: '2026-02-22T08:30:00Z',
    },
  ];

  blogPosts: BlogPostItem[] = [
    {
      id: 'blog-01',
      slug: 'demystifying-ai-prediction-systems-in-business',
      title: 'Demystifying AI Prediction Systems: From Theory to High-Impact Business Outcomes',
      summary: 'How predictive modeling in credit risk, product returns, and healthcare transforms raw operational data into proactive business decisions.',
      content: `Artificial intelligence is fundamentally reshaping how modern enterprises make critical decisions. Rather than relying solely on retrospective reports and gut instinct, forward-thinking organizations use predictive machine learning systems to anticipate events before they occur.

At STDTech Group, we have engineered specialized predictive engines including Loan Approval Prediction, Product Return Forecasting, and Heart Disease Biomarker Assessment. In this article, we explore the core principles that make machine learning models practical, transparent, and trustworthy in production environments.

### 1. The Power of Feature Engineering
A machine learning model is only as effective as the data fed into it. When building our Loan Approval Prediction System, identifying non-linear interactions between an applicant's debt-to-income ratio, credit history stability, and loan duration proved far more valuable than raw income numbers alone.

### 2. Overcoming the Black-Box Dilemma
A common hesitation among business leaders is the inability to understand how AI arrives at a decision. We address this by integrating explainability frameworks (such as SHAP value analysis) directly into user-facing dashboards. When a credit risk score is calculated, the system explicitly highlights the top positive and negative contributing factors.

### 3. Real-Time Deployment Architecture
Training a model in a Jupyter Notebook is straightforward; running it with sub-100 millisecond latency under high concurrent load requires clean software engineering. By containerizing our models with Docker, wrapping them in lightweight asynchronous APIs, and validating inputs with strict schemas, we ensure reliable enterprise performance.`,
      category: 'Artificial Intelligence',
      authorName: 'Harinath Verma',
      readingTime: '5 min read',
      publishedAt: '2026-02-18T10:00:00Z',
      tags: ['AI', 'Machine Learning', 'FinTech', 'Data Science'],
    },
    {
      id: 'blog-02',
      slug: 'building-resilient-web-applications-with-react-and-typescript',
      title: 'Building Resilient, Scalable Web Applications with React & TypeScript',
      summary: 'Key architectural lessons for creating fast, type-safe, and maintainable enterprise web platforms that scale effortlessly.',
      content: `Modern web development demands speed, reliability, and accessibility. Choosing the right architectural foundation early saves months of technical debt down the line.

When architecting the STDTech Group web platform, our team established clear structural rules:
1. **Strict Type Safety:** Using TypeScript across both client and server boundaries eliminates runtime null errors and establishes clear contracts.
2. **Component Modularity:** Extracting reusable components with predictable prop signatures keeps the codebase maintainable as features expand.
3. **Accessibility First:** Prioritizing WCAG AA color contrast, semantic HTML tags, keyboard navigation, and fast Core Web Vitals guarantees an inclusive user experience for all users regardless of device.

By coupling React with Vite and Tailwind CSS, we achieve instant builds and ultra-fast page rendering without unnecessary framework overhead.`,
      category: 'Software Engineering',
      authorName: 'STDTech Editorial Team',
      readingTime: '4 min read',
      publishedAt: '2026-02-25T11:30:00Z',
      tags: ['Web Development', 'React', 'TypeScript', 'Performance'],
    },
    {
      id: 'blog-03',
      slug: 'practical-it-education-bridging-the-academic-industry-gap',
      title: 'Practical IT Education: Bridging the Gap Between Academia and Industry',
      summary: 'Why project-based, hands-on technical training is vital for engineering students in India and across the world.',
      content: `Traditional engineering curricula often emphasize theoretical concepts while lagging behind modern industry toolchains. Students frequently graduate with textbook knowledge of algorithms but lack practical familiarity with Git, containerization, cloud deployments, or real-world database design.

At STDTech Academy, our mission is to empower students through practical, project-centric education. Every course is paired with tangible industry projects, code reviews, and verifiable QR-code certificates.

By building real applications—such as e-commerce backends, AI classifiers, and network security audits—learners develop the problem-solving confidence needed to excel in modern technology careers.`,
      category: 'Education & Careers',
      authorName: 'Akash Verma',
      readingTime: '4 min read',
      publishedAt: '2026-03-01T09:00:00Z',
      tags: ['Education', 'STDTech Academy', 'Career Growth', 'Practical Tech'],
    },
  ];

  contactMessages: ContactMessageItem[] = [
    {
      id: 'msg-01',
      name: 'Vikas Singh',
      email: 'vikas.singh@enterprise.in',
      phone: '9876541230',
      subject: 'Custom Web Application & ERP Consultation',
      service: 'Web & Mobile App Development',
      message: 'We are looking to develop a custom ERP and client portal for our manufacturing business. Would like to discuss timeline and technical approach.',
      status: 'new',
      createdAt: '2026-02-28T16:00:00Z',
    },
  ];

  supportTickets: SupportTicketItem[] = [
    {
      id: 'tkt-01',
      userId: 'usr-customer-01',
      userName: 'Rajesh Gupta',
      userEmail: 'client@stdtechgroup.com',
      subject: 'Inquiry regarding Loan Approval API Integration',
      message: 'Can you provide the swagger documentation and sample payload for integrating the prediction endpoint with our test environment?',
      priority: 'Normal',
      status: 'Open',
      createdAt: '2026-03-02T10:15:00Z',
    },
  ];

  auditLogs: AuditLogItem[] = [
    {
      id: 'log-01',
      userEmail: 'admin@stdtechgroup.com',
      action: 'SYSTEM_BOOT',
      entity: 'Platform',
      details: 'STDTech Group platform initialized in production mode.',
      timestamp: '2026-03-01T00:00:00Z',
    },
    {
      id: 'log-02',
      userEmail: 'admin@stdtechgroup.com',
      action: 'CERTIFICATE_ISSUED',
      entity: 'Certificates',
      details: 'Certificate STDT-2026-00001 generated for student Aditya Sharma.',
      timestamp: '2026-03-01T02:30:00Z',
    },
  ];

  studentEnrollments: StudentEnrollment[] = [
    {
      id: 'enr-01',
      courseId: 'crs-02',
      courseTitle: 'Full-Stack Web & Mobile App Development Bootcamp',
      enrolledAt: '2026-02-01',
      progressPercentage: 100,
      status: 'Completed',
      certificateId: 'STDT-2026-00001',
    },
    {
      id: 'enr-02',
      courseId: 'crs-03',
      courseTitle: 'AI, Machine Learning & Data Science Engineering',
      enrolledAt: '2026-02-15',
      progressPercentage: 45,
      status: 'In Progress',
    },
  ];
}

export const store = new DataStore();
